//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESB2.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityDataModelESB2Container : DbContext
    {
        public EntityDataModelESB2Container()
            : base("name=EntityDataModelESB2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ExceptionEventLogEntry> ExceptionEventLog { get; set; }
        public virtual DbSet<EventLoggerEvent> EventLogLog { get; set; }
        public virtual DbSet<SystemGroup> SystemGroupings { get; set; }
        public virtual DbSet<EquipmentGroup> EquipmentGroupings { get; set; }
        public virtual DbSet<Equipment> EquipmentListing { get; set; }
    }
}
