//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESB2.Database
{
    using System;
    
    public enum EventLoggerEvents : int
    {
        LoginSuccess = 0,
        LoginFail = 1,
        Logout = 2,
        UserCreated = 3,
        UserAccountLocked = 4,
        UserAccountUnlocked = 5,
        UserPasswordChanged = 6,
        InvalidUsername = 7,
        ApplicationStarted = 8,
        ApplicationClosing = 9,
        SystemGroupAdded = 10,
        SystemGroupDeleted = 11,
        EquipmentGroupAdded = 12,
        EquipmentGroupDeleted = 13,
        EquipmentAdded = 14,
        EquipmentDeleted = 15
    }
}
