//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESB2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionEventLogEntry
    {
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public string StackTrace { get; set; }
        public bool IsInnerException { get; set; }
    
        public virtual ExceptionEventLogEntry InnerException { get; set; }
    }
}
