//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESB2.Database
{
    using System;
    
    public enum OperationalStatus : int
    {
        OnLine = 0,
        OffLine = 1,
        StandBy = 2,
        LayUp = 3
    }
}
