//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESB2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusBoardPageRowItem
    {
        public int Id { get; set; }
        public int StatusBoardPageRowId { get; set; }
        public int ItemIndex { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
