//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESB2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin : User
    {
        public byte[] Password { get; set; }
        public System.DateTime LastLogin { get; set; }
        public System.DateTime FailedLoginTimestamp { get; set; }
        public int FailedLoginCount { get; set; }
        public bool AccountLocked { get; set; }
        public bool UserMustChangePassword { get; set; }
    }
}
